### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

GET http://localhost:8080/users
Authorization: Basic arfath1 password

###
POST http://localhost:8080/register
Content-Type: application/json

{
  "username": "arfu2",
  "password": "aaa@123",
  "roles": "USER"
}